public class MySampleApexClass {       //Class definition and body
   public static Integer myValue = 0;  //Class Member variable
   public static String myString = ''; //Class Member variable
   
   public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
	  // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
	  // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;

   }
    public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
	  // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
	  // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;

   }
	public static void demoMethod1(){
	}
	public static void demoMethod2(){
		system.out.println("Method with string variable in side");
	}
	public static void demoMethod3(){		
		if(int i=0;i<=10;i++){
			system.out.println("if condition in the method")
			}			
	}
}
